#%RAML 1.0 DataType
type: object
additionalProperties: false
properties:
  id:
    type: string
    description: A promotion identifier applied for a discounted price.
    required: false
    example: 5C298671