#%RAML 1.0 NamedExample
409 Conflict:
  code: conflict
  message: The request could not be completed due to a conflict with the current state of the target resource. This code is used in situations where the user might be able to resolve the conflict and resubmit the request.
  traceId: 73b309b81fd54d7fb43ead4052210959
  errorId: 79b309b81fd54d7fb43ead4000010959
  dateTime: 2024-04-23T10:00:00Z