#%RAML 1.0 DataType
description: Activity details
type: object
additionalProperties: false
properties:
  date: 
    description: Activity date
    type: datetime-only
    required: false
    example: "2024-06-20T13:43:46"
