#%RAML 1.0 DataType
description: Campaign details
type: object
additionalProperties: false
properties:
  code:
    description: Campaign code
    type: string
    required: false
    example: "27703"
  type:
    description: Campaign type
    type: string
    required: false
    example: "batch"
  name:
    description: Campaign name
    type: string
    required: false
    example: "20240620_USA_OS_WEEKLY_25D_JUNE_062024_REDEMPTION_7"
