#%RAML 1.0 DataType
description: Program details
type: object
additionalProperties: false
properties:
  name:
    description: Program name
    type: string
    required: false
    example: "20240620_USA_OS_WEEKLY_25D_JUNE_062024_REDEMPTION_7"