#%RAML 1.0 DataType
displayName: Onboard Services maximum age requirement definition
description: Onboard Services maximum age requirement
type: object
additionalProperties: false
properties:
  maximum: 
    type: integer
    description: Maximum age
    required: true
