#%RAML 1.0 DataType
displayName: Onboard Services minumum age requirement definition
description: Onboard Services mimumum age requirement
type: object
additionalProperties: false
properties:
  minimum: 
    type: integer
    description: Minimum age
    required: true
