#%RAML 1.0 DataType
displayName: Customer update response
description: Customer update response object
type: partialSuccess
additionalProperties: false
properties:
  goldenId:
    type: goldenId
    description: The customer's golden ID
    required: true
    example: "1000518"
examples: !include ../../examples/customers/update-response.raml