#%RAML 1.0 NamedExample
Get CheckIns response:
  checkIns:
    - passenger:
        id: "150768844"   
      isCompleted: true
      isSecurityPictureProvided: true
    - passenger:
        id: "150768845"   
      isCompleted: true
      isSecurityPictureProvided: true
    - passenger:
        id: "150768846"   
      isCompleted: true
      isSecurityPictureProvided: true