#%RAML 1.0 NamedExample
Payment Options Response:
  paymentOptions:
    - type: DEPOSIT
      transactionId: "250319171330182675"
      dueDate: "2025-03-20"      
      due:
        gross: "100.00"
    - type: FULL
      transactionId: "250319171330182675"
      dueDate: "2025-03-20"
      due:
        gross: "100.00"