#%RAML 1.0 Trait
headers:
  MSC-Username: 
    description: Username to be used for downstream authentication.
    example: abc
    required: true
    minLength: 1
  MSC-Password:
    description: Password to be used for downstream authentication
    example: GBR
    required: true
    minLength: 1
  MSC-Agency-Id:  
    description: Agency ID
    example: TESTUK01
    required: true
    minLength: 1