#%RAML 1.0 NamedExample
Get communications resposne:
  communications:
    - sourceSystem: MARKETO
      id: "487679"
      customer:
        goldenId: "10000062"
      channel: MARKETING SYSTEM
      campaign:
        code: "27703"
        type: batch
        description: COM_20062024_20062024
        name: 20240620_USA_OS_WEEKLY_25D_JUNE_062024_REDEMPTION_7
      activity:
        id: "11066370245"
        date: "2024-06-20T13:43:46"
        attributeDescription: "{\"Campaign Run ID\":108610,\"Step ID\":80171,\"Choice Number\":525556}"
        filterDescription: "*ND"
        excludeDescription: "*ND"
        type:
          id: "7"
          description: "Send Email"
      marketAssetDescrption: "USA"
      leadId: "139148039"
      program:
        id : "20480"
        name: "20240620_USA_OS_WEEKLY_25D_JUNE_062024_REDEMPTION_7"
      creativity:
        code: "102319"
        description: "20240620_USA_OS_WEEKLY_25D_JUNE_062024_REDEMPTION_7.20240620_USA_OS_WEEKLY_25D_JUNE_062024_REDEMPTION_7"
      newsletterAdditionalQuestion: "*ND"

    - sourceSystem: AJO
      id: "TBC"
      customer:
        goldenId: "10000062"
      channel: "TBC"
      activity:
        date: "2024-06-20T13:43:46"
        type:
          description: "TBC"
      marketAssetDescrption: "TBC"
      mergerId: "TBC"
      event:
        type: "TBC"
        date: "2024-06-20T13:43:46"
      producedBy: "SELF"
      url:
        id: "TBC"
        trackingType: "TBC"
      linkTags: "TBC"
      trackerUrlLabel: "TBC"
      interactionType: "TBC"
      entityType: "TBC"
      campaign:
        code: "TBC"
        type: "TBC"
        name: "TBC"
        actionId: "TBC"
        versionId: "TBC"
      message:
        id: "TBC"
        profileId: "TBC"
        executionId: "TBC"
      journey:
        name: "TBC"
        actionId: "TBC"
        actionName: "TBC"
        version:
          id: "TBC"
          instanceId: "TBC"
          nodeId: "TBC"
      batchInstanceId: "TBC"
      sms:
        provider: "SINCH"
        messageType: "TBC"
        inboundMessage: "TBC"
      email:
        domain: "TBC"
        subject: "TBC"
      tags: "TBC"
