#%RAML 1.0 NamedExample
Prepaid Booking Refund Request for excusrions:
  cruise:
    id: "VI20260829SOUSOU"
  excursions:
    - id: "9208604"
      passenger:
        id: "150768845"
    - id: "9208605"
      cabin:
        id: "150768801"
    - id: "9208609"
      cabin:
        id: "150768809"

Prepaid Booking Refund Request for onboard services:
  cruise:
    id: "VI20260829SOUSOU"
  onboardServices:
    - id: "9208606"
      passenger:
        id: "150768846"
    - id: "9208607"
      cabin:
        id: "150768802"

    