#%RAML 1.0 NamedExample
405 Method Not Allowed:
  code: unaccepted_http_method
  message: The method received in the request-line is known by the origin server but not supported by the target resource.
  traceId: 73b309b81fd54d7fb43ead4052210959
  errorId: 79b309b81fd54d7fb43ead4000010959
  datetime: 2024-04-23T10:00:00Z