#%RAML 1.0 NamedExample
424 Failed Dependency:
  code: dependency_failed
  message:  The method could not be performed on the resource because the requested action depended on another action and that action failed.
  traceId: 73b309b81fd54d7fb43ead4052210959
  errorId: 79b309b81fd54d7fb43ead4000010959
  datetime: 2024-04-23T10:00:00Z