#%RAML 1.0 DataType
displayName: User Creation Response
description: Response after attempting the completion of the web identity profile
additionalProperties: false
type: partialSuccessResponse
properties:
  token:
    type: string
    description: The updated token
    required: true
    example: "eyJhbGciOiJIUzI1NiIsIn"
  loginMode:
    type: string
    enum:
      - full
    description: The login mode
    required: true
    example: "full"
  goldenId:
    type: string
    description: The customer golden ID
    required: true
    example: "123456"
  crmasisId:
    type: string
    description: The CRM AS IS ID
    required: true
    example: "CRM38951234"
  name:
    type: string
    description: First name of the customer
    required: true
    example: "sam"
  surname:
    type: string
    description: Last name of the customer
    required: true
    example: "speed"

examples: !include ../../examples/users/post-user-response.raml