#%RAML 1.0 DataType
displayName: item details
description: item details definition
type: passengerDetails|cabinDetails
additionalProperties: false
properties:
  id:
    type: string
    description: Unique identifier for the cruise.
    required: true
    example: "CR123456"
            
         

        
  