#%RAML 1.0 DataType
displayName: Telephone number definition
description: Telephone
type: string
pattern: '^\+[1-9]\d{1,14}$'
examples:
  example 1: "+3922465764"
  example 2: "+3425468764622"
  example 3: "+356123321432"
  