#%RAML 1.0 DataType
displayName: Related item
description: Related item details
type: object
additionalProperties: false
properties:
  id:
    type: string
    description: The ID of the item
    required: false
    example: "ITM0123"