#%RAML 1.0 DataType
displayName: Passenger details
description: Passenger details definition
type: object
additionalProperties: false
properties:
  passengerType:
    description: Passenger Type
    type: !include ../../primitives/passenger-type.raml
    required: false
  adults:
    description: Adult passengers information
    type: object
    required: true
    properties: 
      total: 
        type: integer
        description: Total amount of passengers in this category
        required: true
      details:
        type: array
        description: Passenger information
        required: true
        minItems: 1 
        items:
          type: !include base-passenger-details.raml
          properties:
            number:
              description: Incremental number identifying the passenger within the request
              type: integer
              minimum: 1
              required: true
              example: 1
            age: 
              description: Passenger's age
              type: integer
              minimum: 18
              required: true
            leadPassenger:
              description: Describes whether the passenger is the lead.
              type: boolean
              required: false
              example: false

  children:
    description: Children's passenger information
    type: object
    required: false
    properties: 
      total: 
        type: integer
        description: Total amount of passengers in this category
        required: true
      details:
        type: array
        description: Passenger information
        required: false
        items:
          type: !include base-passenger-details.raml
          properties:
            number:
              description: Incremental number identifying the passenger within the request
              type: integer
              minimum: 1
              required: true
              example: 1
            age: 
              description: Passenger's age
              type: integer
              maximum: 17
              minimum: 0 
              required: true