#%RAML 1.0 NamedExample
Complete Web Identity Profile Request Example:
  name: "John"
  surname: "Wick"
  email: "john.wick@gmail.com"
  dateOfBirth: "1992-03-21"
  gender: MALE
  address:
    countryCode: IR
  mobilePhone: "+356123321432"
  booking:
    number: "55683958"
  createNewMembership: false
  membership:
    number: "123456"
  marketingConsents:
    loyaltyClubEmail: false
  termsAndConditionsConsent: true
  thirdPartyConsent: true
  profilingConsent: true
  privacyConsent: true