#%RAML 1.0 DataType
displayName: Base Port details definition
description: Base Port details
type: object
additionalProperties: false
properties:
  name:
    type: string
    description: The name of the port
    required: false
    example: Miami, United States