#%RAML 1.0 DataType
type: string
enum:
  - PASSPORT
  - BIRTH_CERTIFICATE
  - DRIVERS_LICENSE
  - WORK_PERMIT
  - ATTORNEY_PERMIT
  - VISA
  - NATIONAL_IDENTITY
  - NATIONAL_IDENTITY
description: The document type
example: "PASSPORT"