#%RAML 1.0 DataType
displayName: Onboard Services price amount definition
description: Onboard Services price amount
type: object
additionalProperties: false
properties:
  total:
    type: object
    description: Before, after and tax amounts
    additionalProperties: false
    required: true
    properties:
      beforeDiscount: 
        type: amount
        description: Amount before discount
        required: true
        example: '20.00'
      afterDiscount: 
        type: amount
        description: Amount after discount
        required: true
        example: '10.00'
  tax: 
    type: amount
    description: Tax amount
    required: true
    example: '1.00'