#%RAML 1.0 DataType
displayName: Email definition
description: Email
type: string
pattern: '^\S+@\S+\.\S+$'
examples:
  example 1: abcd@gmail.com
  example 2: abc.def.ijk@hotmail.net
  example 3: abcd@gmail.com.au
  example 4: y@gmail.com
  example 5: y@g.com
  