#%RAML 1.0 NamedExample
Dinning Room Reservation Response:
  slots:
    - time: "07:00"
      date: "2025-03-30"
      isReserved:  false
    - time: "08:00"
      date: "2025-03-30"
      isReserved:  false
    - time: "09:00"
      date: "2025-03-30"
      isReserved:  false
      passengers:
        - id: "150768844"
          reservationId: "71772fdce44411efa2760798658dcf36"
          requestId: "123er34sdf478hty34"
          mealType: "LUNCH"
