#%RAML 1.0 NamedExample
428 Precondition Required:
  code: precondition_required
  message:  The request is expected to be conditional. Try using the If-Match HTTP header.
  traceId: 73b309b81fd54d7fb43ead4052210959
  errorId: 79b309b81fd54d7fb43ead4000010959
  datetime: 2024-04-23T10:00:00Z