#%RAML 1.0 NamedExample
500 Internal Server Error: 
  code: server_error
  message: An internal or downstream error prevented the request from being processed successfully - refer to the error payload for more concrete information.
  traceId: 73b309b81fd54d7fb43ead4052210959
  errorId: 79b309b81fd54d7fb43ead4000010959
  datetime: 2024-04-23T10:00:00Z
  source: 
    name: api-name
    layer: API_SYSTEM