#%RAML 1.0 DocumentationItem
title: CHANGELOG
content: | 
        All notable changes to this project will be documented in this file. <br> <br>
        The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/), and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

        * Version 1
          * Version 1.0.1 (04/03/2025)
            * Added x-client-id-authentication security schema
          * Version 1.0.0 
            * Added basic-authentication, client-id-authentication, oauth2-authentication security schemas