#%RAML 1.0 NamedExample
Unsubscribe Email Request:
  type: "UNSUBSCRIBE"
  goldenId: "123456"
  campaignId: "f7a0dad2-4ca2-48d0-96c5-e4278428435g"
  recipient:
    name: John
    email: "test@test.com"