#%RAML 1.0 DataType
displayName: Amount definition
description: Amount
type: string
pattern: '^\d{1,13}$|^\d{1,13}\.\d{1,5}$'
examples:
  example 1: '1.00'
  example 2: '100.00'
  example 3: '0.90'
  example 4: '500000.00'