#%RAML 1.0 NamedExample
Login Token Upgrade Response:
  token: "eyJhbGciOiJIUzI1NiIsIn"
  loginMode: "full"
  goldenId: "123456"
  crmasisId: "CRM38951234"
  passengerId: "1"
  bookingNumber: "12345"
  name: "sam"
  surname: "speed"