#%RAML 1.0 Library
usage: Library that neatly encapsulates the Error type definition as per the MSC REST API Design guidelines.

types:
  error: !include dataTypes/error.raml

traits:
  baseErrorJsonResponses: !include traits/base-error-json-responses.raml
  baseErrorXmlResponses: !include traits/base-error-xml-responses.raml
  notFoundErrorJsonResponse: !include traits/not-found-error-json-response.raml
  notFoundErrorXmlResponse: !include traits/not-found-error-xml-response.raml
  conditionalErrorJsonResponses: !include traits/conditional-error-json-responses.raml
  conditionalErrorXmlResponses: !include traits/conditional-error-xml-responses.raml
  serverUnreachableErrorJsonResponses: !include traits/server-unreachable-error-json-responses.raml
  serverUnreachableErrorXmlResponses: !include traits/server-unreachable-error-xml-responses.raml