#%RAML 1.0 NamedExample
415 Unsupported Media Type:
  code: invalid_media_type
  message: The payload format is in an unsupported format.
  traceId: 73b309b81fd54d7fb43ead4052210959
  errorId: 79b309b81fd54d7fb43ead4000010959
  dateTime: 2024-04-23T10:00:00Z
  source: 
    name: api-name
    layer: API_SYSTEM