#%RAML 1.0 NamedExample
Get Cabin Slots Example:
  slots:
    - id: "166837"
      isAvailable: true
      startTime: "12:00:00"
      endTime: "13:00:00"
      isAssigned: true
      allocationType: GROUP
    - id: "166838"
      isAvailable: true
      startTime: "13:00:00"
      endTime: "14:00:00"
      isAssigned: true
      allocationType: GROUP
    - id: "166839"
      isAvailable: true
      startTime: "14:00:00"
      endTime: "15:00:00"
      isAssigned: false
    