#%RAML 1.0 NamedExample
Bookings Response:
  bookings:
    - number: "123456"
      email: email.here@test.com
      agencyId: UK123456
      cruiseId: DI20241115MIAMIA
      channel: B2C
      cabinNumber: "10161"
      marketCode: USA
      createdDate: 2025-01-10
      region: CAR
      cruiseLength: 7
      status: BOOKED
      officeCode: USA