#%RAML 1.0 NamedExample
Search Service Requests Emails Attachments Results:
  attachments:
    - fileName: "Allegato 1.txt"
      signedUrl: "https://yourstorageaccount.blob.core.windows.net/yourcontainer/1-3REUJLZ_1-3REUJIB_Allegato 1.txt?sv=2021-08-06&st=2024-10-05T00%3A00%3A00Z&se=2024-10-06T00%3A00%3A00Z&sr=b&sp=r&sig=signature"
    - fileName: "WR.jpg"
      signedUrl: "https://yourstorageaccount.blob.core.windows.net/yourcontainer/1-3REUJLZ_1-3REUJIB_WR.jpg?sv=2021-08-06&st=2024-10-05T00%3A00%3A00Z&se=2024-10-06T00%3A00%3A00Z&sr=b&sp=r&sig=signature"
    - fileName: "Notes.pdf"
      signedUrl: "https://exampleblobstorage.blob.core.windows.net/container/1-3REUJLZ_1-3REUJIB_Notes.pdf?sv=2021-04-10&st=2022-10-01T00%3A00%3A00Z&se=2022-10-02T00%3A00%3A00Z&sr=b&sp=r&sig=signature"