#%RAML 1.0 NamedExample

Search Service Requests Results:
  serviceRequests: 
    - "number": "1-73366738"
      "id": "1-17OI4Y"
      "customer": 
        "goldenId": "3425468764622"
        "name": "John"
        "surname": "Wick"      
      "travelAgency": "*ND"
      "marketCode": "1-2Q0N"
      "createdDateTime": "2022-01-10T11:40:55Z"
      "createdBy": "CRMASIS"
      "chargeDate": "2022-01-12"
      "closureDateTime": "2022-07-04T12:45:44Z"
      "employeeOwner": "CRMASIS"
      "acquisitionChannel": ""
      "status": "0-3248"
      "outcome": "*ND"
      "booking": 
        "number": "000"      
      "sellCruise": ""
      "numberOfPassengers": 3
      "contactReason": "*ND"
      "periodOfInterest": ""
      "travelCondition": ""
      "destination": ""
      "campaignName": ""
      "inboundCampaignCode": ""
      "outboundCampaignCode": ""
      "category": "Info"
      "subCategory": "General - Commercial"
      "type": "Info On Website"
      "workgroup": "*NON DEFINITO"
      "priority": "0-3236"
      "amountClaimed": "500000.00"
      "amountOffered": "500000.00"
      "currencyCode": "EUR"
      "mode": "*Non Definito"
      "touchPoint": "assistenzaclienti"
      "relatedServiceRequest": "2-15104374254"
      "refusalReason": "excommunicado"
  "_pagination": 
    "currentPage": 1
    "pageSize": 1
    "totalPages": 1
    "totalItems": 1

Search Service Requests Minimum Results:
  serviceRequests: 
    - "customer": 
        "goldenId": "3425468764622"
  "_pagination": 
    "currentPage": 1
    "pageSize": 1
    "totalPages": 1
    "totalItems": 1