#%RAML 1.0 NamedExample
Search Service Requests Emails Results:
  emails:
    - id: "2-A77HOQG"
      serviceRequest:
        number: "2-22203669119"
        id: "2-A77HOQN"
        createdDate: "2024-07-08T11:21:30Z"
        createdBy: "0-1"
        lastUpdateDate: "2024-07-08T13:21:30Z"
        lastUpdateBy: "2-976ZNLG"
        modificationNumber: 8
        conflictId: "0"
      createdDate: "2024-07-08T11:21:30Z"
      threadId: "2-A6VU59I"
      parentId: "2-A77HOQG"
      type: "Email - Inbound"
      catalogId: "0-7775H"
      format: "Plain Text"
      bodyLanguage: "ENU"
      mimeType: "utf-8"
      subject: "Re: 51806959 [SR Number: 2-22184095019]"
      body: "Thanks for getting back to me and keeping me informed Craig, I appreciate it 😁 hope you have a great day! Sent from my iPhone ..."
      isAttachmentIncluded: false
      isForwarded: true
      isManuallyEdited: true

      recipient:
        email: "customerservice@msccruises.co.uk"
        name: "MSC Customer Service"
        cc: "manager@msccruises.co.uk"
        bcc: "admin@msccruises.co.uk"

      sender:
        email: "client@example.com"
        name: "John Doe"
        to: "customerservice@msccruises.co.uk"


      databaseInfo:
        lastUpdateDate: "2024-07-08T11:21:30Z"
        lastUpdateChannelSource: "Object Manager - Default"

    - id: "2-A76Z8U5"
      serviceRequest:
        number: "2-22184095019"
        id: "2-A6VU59N"
        createdDate: "2024-05-08T13:21:30Z"
        createdBy: "0-2"
        lastUpdateDate: "2024-07-08T10:21:30Z"
        lastUpdateBy: "2-976ZXYZ"
        modificationNumber: 12
        conflictId: "1"
      createdDate: "2024-05-08T13:21:30Z"
      threadId: "2-A6VU59I"
      parentId: "2-A76Z8U5"
      type: "Email - Outbound"
      catalogId: "0-7775I"
      format: "HTML"
      bodyLanguage: "ENG"
      mimeType: "utf-8"
      subject: "RE: 51806959 [SR Number: 2-22184095019]"
      body: "<p>Dear Customer,</p><p>We are currently experiencing issues ...</p>"
      isAttachmentIncluded: true
      isForwarded: false
      isManuallyEdited: false

      recipient:
        email: "client@example.com"
        name: "John Doe"
        cc: ""
        bcc: ""

      sender:
        email: "customerservice@msccruises.co.uk"
        name: "MSC Customer Service"
        to: "client@example.com"

      databaseInfo:
        lastUpdateDate: "2024-07-08T10:21:30Z"
        lastUpdateChannelSource: "System Update"

  "_pagination": 
    "currentPage": 1
    "pageSize": 1

Search Service Requests Emails Empty Results:
  emails: []
  "_pagination": 
    "currentPage": 1
    "pageSize": 1