#%RAML 1.0 NamedExample
Get Customer by Golden ID Results:
  name: GARRETZENOTEST
  surname: DOOLEYZENOTEST
  dateOfBirth: 2001-08-05
  gender: "MALE"
  email: abcd@gmail.com.au
  phone: "+341234567890"
  mobilePhone: "+3412345677"
  address:
    addressLine1: TEST ADDRESS
    town: DARLINGTON
    districtName: VIERA
    region: CAMPANIA
    province: RM
    state: GBR
    postCode: "28001"
    country: ITALY
  marketingConsents:
    phone: true
    mobilePhone: true
    email: true
  thirdPartyConsent: false
  profilingConsent: false
