#%RAML 1.0 NamedExample
503 Service Unavailable:
  code: service_unavailable
  message: The server is currently unable to handle the request due to a temporary overloading or maintenance of the server.
  traceId: 73b309b81fd54d7fb43ead4052210959
  errorId: 79b309b81fd54d7fb43ead4000010959
  dateTime: 2024-04-23T10:00:00Z
  source: 
    name: api-name
    layer: API_SYSTEM